### ISSUE TITLE
how to compile and run

### ISSUE THREAD

**Issue by cshubhamdhanetia** [programble/tetrasm#4]
I am very new to this......kindly teach me how to compile and run steps by steps..thank you :)

**Comment by causal-agent** [comment]
Which platform are you on?

**Comment by cshubhamdhanetia** [comment]
nasm...i know how to compile one asm file..but here there are many...dont know what to do and how to do

**Comment by causal-agent** [comment]
There are instructions in the [README](https://github.com/programble/tetrasm#build).
